import { AspectRatio } from "@/components/ui/aspect-ratio";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
} from "@/components/ui/card";
import { APP_NAME, VideoExamples } from "@/constants/layout";
import { ArrowRight } from "lucide-react";
import { useTranslations } from "next-intl";
import Image from "next/image";
import Link from "next/link";
import React from "react";

type Props = {};
interface VideoExample {
  src: string;
  prompt: string;
}

export default function Example({}: Props) {
  const t = useTranslations();
  return (
    <div className="container space-y-3 md:space-y-8">
      {/* <h2 className="text-center">
        Videos Created with Kling AI
        <span className="text-lg font-semibold text-blue-500"></span>
      </h2> */}
      <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl text-center">
        {APP_NAME} Video Examples
      </h1>

      <p className="text-lg  text-muted-foreground  text-center w-full">
        Explore {APP_NAME} video generated by kling ai
      </p>

      <div className="columns-2 md:columns-3 space-y-3 md:space-y-8 h-full">
        {/* mt-[3rem] grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3 md:gap-8 */}
        {/* song */}
        {t.raw("ExamplePage.videoExample").map((video: VideoExample) => (
          <Card key={video.src} className="relative flex h-full flex-col">
            <CardHeader className="relative overflow-hidden rounded-t-lg px-6 py-2">
              <video
                className="rounded"
                preload="auto"
                controls
                src={`${video.src}`}
              ></video>
              <div>{/* className="aspect-w-16 aspect-h-9" */}</div>
            </CardHeader>

            <CardFooter className="flex flex-1 flex-col p-4">
              {/* meta tag */}

              <div className="flex items-center justify-between">
                <Link
                  className="flex items-center justify-center gap-2 transition-all duration-200 hover:text-blue-500"
                  href={`/examples`}
                >
                  <p className=" text-md font-bold">{video.prompt}</p>
                  {/* <ArrowRight className="h-4 w-4" /> */}
                </Link>
              </div>

              <p className="font-mono text-sm">
                Created By{" "}
                <a href="/" className="font-semibold text-indigo-500">
                  Kling AI
                </a>{" "}
              </p>
              {/* <div className="flex items-center justify-between gap-3">
                <Button variant="outline">Download</Button>
              </div> */}
            </CardFooter>
          </Card>
        ))}
      </div>
    </div>
  );
}
